const {readFileSync, writeFileSync} = require('fs')
const first = readFileSync('./content/file.txt', 'utf8')
const second = readFileSync('./content/second.txt', 'utf8')
console.log(first, second)
writeFileSync('./content/result.txt', `here is result`, { falg: 'a' })